# Generated by Django 4.1 on 2022-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='attachments')),
                ('user_name', models.CharField(max_length=50)),
                ('provider', models.CharField(choices=[('adobe', 'Adobe'), ('liveramp', 'LiveRamp'), ('neustar', 'Neustar'), ('oracle blue kai', 'Oracle Blue Kai'), ('salesforce (krux)', 'Salesforce (Krux)')], max_length=50)),
            ],
        ),
    ]
